// app/robots.js
export default function robots() {
  return {
    rules: [
      {
        userAgent: '*',
        allow: '/',
        disallow: [
          '/api/',
          '/admin/',
          '/dashboard/',
          '/sign-in',
          '/sign-up',
          '/checkout',
          '/cart',
          '/profile',
          '/account',
          '/orders',
          '/wishlist',
          '/search?*',
          '/filter?*',
          '/*?*utm_*',
          '/*?*ref=*',
          '/*?*fbclid=*',
          '/*?*gclid=*',
          '/private/',
          '/temp/',
          '/test/',
          '/*.pdf',
          '/*.doc',
          '/*.docx',
          '/*.xls',
          '/*.xlsx',
          '/*.json',
          '/*.xml',
          '/*.txt',
        ],
      },
      {
        userAgent: 'Googlebot',
        allow: '/',
        disallow: [
          '/api/',
          '/admin/',
          '/dashboard/',
          '/sign-in',
          '/sign-up',
          '/checkout',
          '/cart',
          '/profile',
          '/account',
          '/orders',
          '/wishlist',
          '/private/',
        ],
      },
      {
        userAgent: 'Bingbot',
        allow: '/',
        disallow: [
          '/api/',
          '/admin/',
          '/dashboard/',
          '/sign-in',
          '/sign-up',
          '/checkout',
          '/cart',
          '/profile',
          '/account',
          '/orders',
          '/wishlist',
          '/private/',
        ],
      },
    ],
    sitemap: 'https://hamroeshop.com/sitemap.xml',
    host: 'https://hamroeshop.com',
  };
}